dist: trusty
sudo: false

language: node_js
node_js:
  - '10'

addons:
  chrome: stable

env:
  global:
    CODECOV_TOKEN=$CODECOV_TOKEN

before_script:
  - npm install
jobs:
  include:
    - stage: Test coverage
      script:
        - npm run test -- --watch=false --no-progress --codeCoverage=true --browsers=ChromeHeadlessNoSandbox
      after_script:
         - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./node_modules/.bin/codecov; fi
